### PR TITLE
Split baseline so it can load in OpenSSL isn

### PR DESCRIPTION
**Pull request by pdebruic**

### CODE REVIEW

**Comment by noha** [comment]
Gemstone is failing. It says no tests were executed

**Comment by pdebruic** [comment]
Yeah I need to fix it and ran out of time yesterday.  Do you want to close this and I can re-open it when I get back to it?  I'm fine with it open and needing work.

**Comment by noha** [comment]
I'm fine, too. Just wanted to notify failing build. I'm happy you care

**Comment by noha** [comment]
This is now old and seems to became obsolete. Reopen if needed

**Pull request closed without merging**
