### PR TITLE
Adding RS256 signature verification.

### PR DESCRIPTION
**Pull request by Ironirc**

### CODE REVIEW

**Comment by noha** [comment]
Thanks! Where are the LcRSA and companion classes. With the PR we add a dependency which is not resolved

**Comment by Ironirc** [comment]
LcRSA  stems from https://github.com/PierceNg/OpenSSL-Pharo
Is there a way to explicitly declare this dependency in the code or package definition?

**Comment by Ironirc** [comment]
> Thanks! Where are the LcRSA and companion classes? With the PR we add a dependency which is not resolved

I see the "resolve conflicts" pop up. Am I supposed to take action on this?

**Comment by noha** [comment]
Please have a look at #10 where your changes are incorporated

**Pull request closed without merging**
